# Generated by Django 5.0.7 on 2024-07-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('account_number', models.PositiveBigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_name', models.CharField(max_length=100)),
                ('phone2', models.IntegerField(null=True)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('country2', models.CharField(max_length=100)),
                ('city2', models.CharField(max_length=100)),
                ('account_number2', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
